---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive backend file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "installing node"
  shell: |
      cd /home/ubuntu/backend
      npm i

- name: "excuting with pm"
  shell: |
      cd /home/ubuntu/backend/dist
      pm2 stop default
      pm2 start main.js

- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
